apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-copy-plugins
  labels:
    app: sonarqube
data:
  copy_plugins.sh: |-
      #! /bin/sh
      cp /opt/sonarqube/extensions/plugins/tmp/*.jar /opt/sonarqube/extensions/plugins/
      /opt/sonarqube/bin/run.sh


