kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-postgresql
  labels:
    app: sonarqube-postgresql
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
