kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-pvc
  labels:
    app: sonarqube
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"        
