apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql
  labels:
    app: sonarqube-postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: sonarqube-postgresql
