apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube

spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: sonarqube
  selector:
    app: sonarqube
  loadBalancerSourceRanges: [0.0.0.0/0]

